{"level": "WARNING", "timestamp": "2024-08-24T17:03:29.402640+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:29.402640+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:29.402640+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:29.402640+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:29.589056+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:29.589056+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:03:29.589056+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:29.589056+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:29.589056+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:29.589056+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:29.807860+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:29.808864+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:03:29.808864+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:29.808864+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:29.808864+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:29.808864+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:29.976775+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:29.976775+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:03:29.976775+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:29.977774+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:29.977774+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:29.977774+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:30.138564+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:30.138564+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:03:30.138564+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:30.138564+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:30.138564+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:30.138564+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:30.332683+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:30.332683+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:03:30.332683+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:30.332683+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:30.332683+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:30.332683+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:06:53.253735+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:06:53.253735+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:06:53.253735+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:06:53.253735+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 32, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:06:53.253735+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 33, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:06:53.253735+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 36, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 38, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:06:54.261141+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:06:54.261141+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:06:54.261141+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:06:54.261141+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 32, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:06:54.261141+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 33, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:06:54.261141+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 36, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 38, "thread_name": "MainThread"}
