{"level": "ERROR", "timestamp": "2024-08-24T17:02:31.295850+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "logger": "my_app", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:02:31.545664+00:00", "message": "Debug message", "logger": "my_app", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:02:31.545664+00:00", "message": "Info message", "logger": "my_app", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:02:31.545664+00:00", "message": "Warning message", "logger": "my_app", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:02:31.545664+00:00", "message": "Error message", "logger": "my_app", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:02:31.546664+00:00", "message": "Critical message", "logger": "my_app", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:02:31.546664+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "logger": "my_app", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:02:31.826599+00:00", "message": "Debug message", "logger": "my_app", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:02:31.826599+00:00", "message": "Info message", "logger": "my_app", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:02:31.826599+00:00", "message": "Warning message", "logger": "my_app", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:02:31.826599+00:00", "message": "Error message", "logger": "my_app", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:02:31.826599+00:00", "message": "Critical message", "logger": "my_app", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:02:31.826599+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "logger": "my_app", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:13.134078+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:13.134078+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:03:13.135077+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:13.135077+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:13.135077+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:13.135077+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:13.547394+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:13.547394+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:03:13.547394+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:13.547394+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:13.547394+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:13.547394+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:13.809568+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:13.809568+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:03:13.809568+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:13.809568+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:13.809568+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:13.809568+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:14.488305+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:14.488305+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:03:14.488305+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:14.488305+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:14.488305+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:14.488305+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:28.906056+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:28.906056+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "timestamp": "2024-08-24T17:03:28.906056+00:00", "message": "Warning message", "module": "logging_src", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:28.906056+00:00", "message": "Error message", "module": "logging_src", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "timestamp": "2024-08-24T17:03:28.906056+00:00", "message": "Critical message", "module": "logging_src", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "timestamp": "2024-08-24T17:03:28.906056+00:00", "message": "Exception message\nTraceback (most recent call last):\n  File \"e:\\logging tests\\logging_src.py\", line 34, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "module": "logging_src", "function": "main", "line": 36, "thread_name": "MainThread"}
{"level": "DEBUG", "timestamp": "2024-08-24T17:03:29.402640+00:00", "message": "Debug message", "module": "logging_src", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "timestamp": "2024-08-24T17:03:29.402640+00:00", "message": "Info message", "module": "logging_src", "function": "main", "line": 28, "thread_name": "MainThread"}
